### ISSUE TITLE
Set up environment & check access

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ffj#1]

**Comment by joshdarby** [comment]
@MirandaEcho Do we know if they're still hosted with Bluehost? 1Pass says the account info is from 2014, and it also doesn't work 😖

**Comment by joshdarby** [comment]
@MirandaEcho Do we want to set up a staging site for them?

**Comment by joshdarby** [comment]
Staging: http://silver-volcano.flywheelstaging.com/
