### ISSUE TITLE
Rename child theme from `sirf` to `ffj`

### ISSUE THREAD

**Issue by joshdarby** [INN/umbrella-ffj#12]

**Comment by benlk** [comment]
Renaming the child theme dir will require re-activation of the child theme, and that will probably require reconfiguration of all widgets and settings in Largo's Theme Options.

If we wanted to change the user-facing labels in `style.css`, and leave a note in `wp-content/themes/README.md` to explain why the theme dir name is `sirf`, that would be okay. We've done it in https://github.com/INN/umbrella-inndev/tree/master/wp-content/themes before.
