### ISSUE TITLE
Homepage CSS updates

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ffj#3]
- [x] Center main nav items
- [x] Increase size of subscribe button in right margin of homepage

**Comment by joshdarby** [comment]
> Increase size of subscribe button in right margin of homepage

@MirandaEcho This button is being brought in from an iframe so we can't update the styling for it. Looks like it's coming from btn.createsend1.com

Could we ask Roddy if we could have access to whatever platform is making it? Maybe we can update the styling from there.

**Comment by MirandaEcho** [comment]
@joshdarby are we able to tell where its coming from?

**Comment by joshdarby** [comment]
@MirandaEcho No, all we can see is it's coming from btn.createsend1.com. That's why it might be a good idea to ask Roddy for access to whatever platform it is.

**Comment by joshdarby** [comment]
What's interesting about the subscribe button is it appears to be from 2013, and I can't actually find the settings for it anywhere now, even though I'm looking where this article says to 🤔 

https://www.campaignmonitor.com/blog/new-features/2013/02/say-hello-to-the-subscribe-button/

**Comment by joshdarby** [comment]
@MirandaEcho The staging site has been updated with a newer form with a button that matches the styling of all other buttons on the page

![Screen Shot 2020-02-21 at 3 51 04 PM](https://user-images.githubusercontent.com/18353636/75070834-11f6d880-54c2-11ea-841c-3a68d26f91d5.png)
